### ISSUE TITLE
Rijndael256Encryptor decrypt does not work correcly

### ISSUE THREAD

**Issue by kYem** [ambta/DoctrineEncryptBundle#11]
256 version does not handle . `"<ENC>"` string that was added when encrypting.

128 does remove it before decrypting and seems to fix the issue on 256 too.

Can anyone explain what's the point of `<ENC>` adding after encrypting data?

**Comment by ambta** [comment]
Hi kYem, thanks for noticing, we will fix this soon.

The <ENC> tag is used to see whether the data is already encrypted or not.
You can decrypt/encrypt the database and put unencrypted data in the database the handler knows what is en what is not encrypted, so it does not accidentally encrypt/decrypt data that may have not been encrypted/decrypted yet.

**Comment by rajesh-vi** [comment]
is there any news on this bug fix?

**Comment by dev-marcel** [comment]
the 3th of november we will bring a big update, i will fix this bug today.

**Comment by dev-marcel** [comment]
Fixed in commit: c2f3403b04b911c6cefd49e2f2e1bc48eb424e59 
Release: https://github.com/ambta/DoctrineEncryptBundle/releases/tag/2.5.4
