### ISSUE TITLE
PHP 7.2 - the requested PHP extension mcrypt is missing from your system.

### ISSUE THREAD

**Issue by kironet** [ambta/DoctrineEncryptBundle#38]

**Comment by Jeordy** [comment]
mcrypt is deprecated as from PHP 7.1 and up. This bundle really needs an update.

**Comment by gastonnina** [comment]
I think a good alternative is migrate the code to openssl it works in both php 5.6+ and 7.1+

http://php.net/manual/en/function.openssl-encrypt.php

**Comment by steveWinter** [comment]
@dev-marcel recently merged PRs make this issue redundant now
