### ISSUE TITLE
Warning: ReflectionProperty::getValue() expects exactly 1 parameter, 0 given

### ISSUE THREAD

**Issue by daysleeperrr** [ambta/DoctrineEncryptBundle#8]
After installing DoctrineEncryptBundle, applying all configurations in settings.yml and adding the @Encrypted annotation to my entities, I try to add a new record via a form in my project (which worked before the encryption bundle was installed). I assumed the field in which the encrypted data is stored should be Blob, so I changed my secret fields from varchar to blob (correct me if I'm wrong about this).

The error (Warning: ReflectionProperty::getValue() expects exactly 1 parameter, 0 given) occurs in vendor\ambta\doctrine-encrypt-bundle\Ambta\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber.php at line 256.

Can anyone point me in the right direction?

**Comment by PH-Lars** [comment]
Hi daysleeper,

If I'm right you should keep the values as strings:

 /**
     \* @var string
     \* @Constraints\NotBlank()
     \* @Constraints\Regex(
     \*     pattern="/^([^0-9]+)$/",
     \*     match=true,
     \*     message="No number field"
     \* )
     *
     \* @Encrypted
     \* @ORM\Column(name="name", type="string", length=256, nullable=true)
     */
    private $name;

In fact, all values which you would like to encrypt should be string. (so date objects and integers too) The encrypted data is not saved as plain bytes to the database for this bundle.

**Comment by daysleeperrr** [comment]
Thanks a lot, this suggestion has resolved my issue!
